import { Hunt, HuntSecrets } from "./types";

export const ICAT_2026_HUNT_ID = "icat-2026";

export const ICAT_2026_HUNT_DATA: Hunt = {
  id: ICAT_2026_HUNT_ID,
  name: "ICAT Bangalore Cyber Hunt 2026",
  slug: "icat-2026",
  status: "active",
  theme: "cyberpunk-vault",
  startingNodeId: "202",
  totalFloors: 5,
  floors: [
    {
      id: "floor-1",
      floorNumber: 1,
      name: "Floor 1 - Ground Level (Reception, Labs, Canteen & Audi)",
      shortName: "FL 1",
      nodeIds: ["Reception", "Audi", "Canteen", "Textile Lab", "Photo Lab"],
    },
    {
      id: "floor-2",
      floorNumber: 2,
      name: "Floor 2 - Digital Labs & Vice Principal Cabin",
      shortName: "FL 2",
      nodeIds: ["202", "201", "206", "Vice principal cabin"],
    },
    {
      id: "floor-3",
      floorNumber: 3,
      name: "Floor 3 - Studios, Library & Staff Lunch",
      shortName: "FL 3",
      nodeIds: ["305", "306", "Library", "Staff Lunch"],
    },
    {
      id: "floor-4",
      floorNumber: 4,
      name: "Floor 4 - Mainframes, Audio & Staff Room",
      shortName: "FL 4",
      nodeIds: ["401A", "401B", "402", "Staff room"],
    },
    {
      id: "floor-5",
      floorNumber: 5,
      name: "Floor 5 - Visual Arts, Fashion Lab & Game Lounge",
      shortName: "FL 5",
      nodeIds: ["503", "Game Lounge", "F.L."],
    },
  ],
  teams: {
    RED: {
      id: "RED",
      name: "Red Squadron",
      color: "red",
      hex: "#FF2A55",
      routeId: "P1",
      badge: "◈",
    },
    WHITE: {
      id: "WHITE",
      name: "White Phantoms",
      color: "white",
      hex: "#E2E8F0",
      routeId: "P2",
      badge: "◇",
    },
    BLACK: {
      id: "BLACK",
      name: "Black Ops",
      color: "black",
      hex: "#64748B",
      routeId: "P3",
      badge: "◆",
    },
    CYAN: {
      id: "CYAN",
      name: "Cyan Cyber",
      color: "cyan",
      hex: "#00F0FF",
      routeId: "P1",
      badge: "❖",
    },
    BLUE: {
      id: "BLUE",
      name: "Blue Sentinels",
      color: "blue",
      hex: "#3B82F6",
      routeId: "P2",
      badge: "⬡",
    },
  },
  routes: {
    P1: {
      id: "P1",
      name: "Route Alpha (P1)",
      nodes: [
        "202",
        "Vice principal cabin",
        "401B",
        "Staff room",
        "306",
        "Staff Lunch",
        "Game Lounge",
        "Textile Lab",
        "401A",
        "F.L.",
        "201",
        "Audi",
      ],
    },
    P2: {
      id: "P2",
      name: "Route Beta (P2)",
      nodes: [
        "202",
        "Game Lounge",
        "503",
        "Staff Lunch",
        "305",
        "Staff room",
        "402",
        "Reception",
        "401A",
        "Canteen",
        "Library",
        "Audi",
      ],
    },
    P3: {
      id: "P3",
      name: "Route Gamma (P3)",
      nodes: [
        "202",
        "Photo Lab",
        "Staff room",
        "306",
        "Library",
        "503",
        "305",
        "Staff Lunch",
        "401A",
        "206",
        "Reception",
        "Audi",
      ],
    },
  },
  nodes: {
    "202": {
      id: "202",
      name: "202",
      floorId: "floor-2",
      type: "NORMAL",
      position: { x: 35, y: 40 },
      riddle: {
        title: "Starting Point: Genesis Station (Room 202)",
        text: "You are currently at Room 202. Present your squad identity to the invigilator in Room 202 to verify your start, receive your launch cipher, and unlock your first destination!",
        hint: "Locate Room 202 on Floor 2. Request the launch cipher to begin.",
      },
      codeSource: "TEACHER",
      nextNodes: ["Vice principal cabin", "Game Lounge", "Photo Lab"],
      puzzleLocation: {
        clue: "Physical Fragment ALPHA is cached under the animation lightbox in Room 202.",
        hint: "Lower cabinet bay.",
        pieceId: "PIECE_ALPHA",
      },
    },
    "Vice principal cabin": {
      id: "Vice principal cabin",
      name: "Vice principal cabin",
      floorId: "floor-2",
      type: "NORMAL",
      position: { x: 75, y: 35 },
      riddle: {
        title: "The Executive Sanctum",
        text: "Where campus leadership charters are reviewed. Present your squad status respectfully to the executive in the Vice Principal Cabin.",
        hint: "Floor 2 Vice Principal Cabin. Ask the executive for the clearance cipher.",
      },
      codeSource: "TEACHER",
      nextNodes: ["401B"],
      puzzleLocation: {
        clue: "Physical clue hidden near the entrance plaque of the Vice Principal Cabin.",
        hint: "Beside the executive directory.",
        pieceId: "PIECE_BETA",
      },
    },
    "401B": {
      id: "401B",
      name: "401B",
      floorId: "floor-4",
      type: "NORMAL",
      position: { x: 70, y: 55 },
      riddle: {
        title: "Virtual Reality Bay",
        text: "Where headsets simulate distant dimensions. Scour the room for a hidden cipher token near the sensor tracking table.",
        hint: "Floor 4, Room 401B. Inspect the VR headset staging table.",
      },
      codeSource: "HIDDEN",
      nextNodes: ["Staff room"],
      puzzleLocation: {
        clue: "Fragment taped under the primary VR tracking stand in Room 401B.",
        hint: "Right support strut.",
        pieceId: "PIECE_GAMMA",
      },
    },
    "Staff room": {
      id: "Staff room",
      name: "Staff room",
      floorId: "floor-4",
      type: "NORMAL",
      position: { x: 30, y: 45 },
      riddle: {
        title: "Staff Room Nexus",
        text: "Where instructors coordinate academic schedules. Look discreetly for the cipher token placed near the central reference desk.",
        hint: "Floor 4 Staff Room. Check near the faculty notice board.",
      },
      codeSource: "HIDDEN",
      nextNodes: ["306", "402"],
      puzzleLocation: {
        clue: "Secured near the faculty schedule board in Staff Room.",
        hint: "Lower shelf.",
        pieceId: "PIECE_DELTA",
      },
    },
    "306": {
      id: "306",
      name: "306",
      floorId: "floor-3",
      type: "NORMAL",
      position: { x: 75, y: 45 },
      riddle: {
        title: "Interface Architecture (Room 306)",
        text: "Where wireframes transform into digital interactions. Request clearance from the faculty coordinator in Room 306.",
        hint: "Floor 3, Room 306. Inquire with the lab supervisor.",
      },
      codeSource: "TEACHER",
      nextNodes: ["Staff Lunch"],
      puzzleLocation: {
        clue: "Fragment placed behind the UI design whiteboard in Room 306.",
        hint: "Behind the marker tray.",
        pieceId: "PIECE_EPSILON",
      },
    },
    "Staff Lunch": {
      id: "Staff Lunch",
      name: "Staff Lunch",
      floorId: "floor-3",
      type: "NORMAL",
      position: { x: 50, y: 70 },
      riddle: {
        title: "The Refreshment Outpost",
        text: "Where faculties recharge between lectures over coffee and meals. A hidden cipher is placed near the refreshment counter.",
        hint: "Floor 3 Staff Lunch Room. Search the refreshment shelf.",
      },
      codeSource: "HIDDEN",
      nextNodes: ["Game Lounge", "305", "401A"],
      puzzleLocation: {
        clue: "Fragment taped under the side utility counter in Staff Lunch Room.",
        hint: "Underneath the corner counter.",
        pieceId: "PIECE_ZETA",
      },
    },
    "Game Lounge": {
      id: "Game Lounge",
      name: "Game Lounge",
      floorId: "floor-5",
      type: "NORMAL",
      position: { x: 25, y: 45 },
      riddle: {
        title: "The Gamer's Haven",
        text: "Where controllers click and high scores reign supreme. Check near the console display stations for your squad cipher.",
        hint: "Floor 5 Game Lounge. Inspect the console shelf.",
      },
      codeSource: "HIDDEN",
      nextNodes: ["Textile Lab", "503"],
      puzzleLocation: {
        clue: "Fragment concealed behind the retro console display in Game Lounge.",
        hint: "Beside the arcade TV cabinet.",
        pieceId: "PIECE_ETA",
      },
    },
    "Audi": {
      id: "Audi",
      name: "Audi",
      floorId: "floor-1",
      type: "FINAL",
      position: { x: 50, y: 20 },
      riddle: {
        title: "FINAL DESTINATION: Campus Auditorium",
        text: "All paths converge at the Grand Auditorium! Assemble all physical puzzle pieces retrieved across campus to reveal the ultimate victory key and claim the ICAT 2026 Grand Trophy!",
        hint: "Enter the Auditorium on Floor 1 and submit the ultimate victory cipher.",
      },
      codeSource: "HIDDEN",
      nextNodes: [],
      puzzleLocation: {
        clue: "THE MASTER PRIZE: Present your completed physical puzzle to the Grand Arbiter on the Auditorium stage.",
        hint: "Victory awaits!",
        pieceId: "PIECE_OMEGA",
      },
    },
    "201": {
      id: "201",
      name: "201",
      floorId: "floor-2",
      type: "NORMAL",
      position: { x: 25, y: 40 },
      riddle: {
        title: "The Sketching Canvas (Room 201)",
        text: "Where line, perspective and shading begin. Ask the foundation instructor for the clearance cipher.",
        hint: "Floor 2, Room 201. Inquire with the studio supervisor.",
      },
      codeSource: "TEACHER",
      nextNodes: ["Audi"],
      puzzleLocation: {
        clue: "Fragment secured behind the drafting board in Room 201.",
        hint: "Left easel support.",
        pieceId: "PIECE_KAPPA",
      },
    },
    "F.L.": {
      id: "F.L.",
      name: "F.L.",
      floorId: "floor-5",
      type: "NORMAL",
      position: { x: 70, y: 45 },
      riddle: {
        title: "Fashion & Film Lab (F.L.)",
        text: "Where mannequins, couture patterns and cameras capture form. Search near the master drafting table.",
        hint: "Floor 5 Fashion Lab (F.L.). Check the pattern drafting table.",
      },
      codeSource: "HIDDEN",
      nextNodes: ["201"],
      puzzleLocation: {
        clue: "Fragment placed beneath the master pattern table in Fashion Lab.",
        hint: "Lower storage shelf.",
        pieceId: "PIECE_IOTA",
      },
    },
    "401A": {
      id: "401A",
      name: "401A",
      floorId: "floor-4",
      type: "BOSS",
      position: { x: 50, y: 25 },
      riddle: {
        title: "Sector 401A [BOSS ENCOUNTER: Unity Challenge]",
        text: "WARNING: High-security cyber defense active! Travel to Room 401A. The Unity Arcade Challenge Station is loaded on the workstation. Achieve >= 850 PTS in the Unity game to receive your clearance cipher and proceed to the next rooms!",
        hint: "Play the Unity Arcade Game in Room 401A. Score >= 850 PTS to unlock the secret cipher to decrypt this sector and unlock your next route nodes!",
      },
      codeSource: "MINIGAME",
      nextNodes: ["F.L.", "Canteen", "206"],
      puzzleLocation: {
        clue: "Physical Boss Fragment DELTA is secured beside the main network switch cabinet in Room 401A.",
        hint: "Check the lower cable conduit casing.",
        pieceId: "PIECE_DELTA",
      },
      minigame: {
        gameId: "401A_UNITY_OVERRIDE",
        minimumScore: 850,
        title: "Unity Cyber Mainframe Override",
        instructions: "Play the Unity game in Room 401A or online. Achieve >= 850 PTS to decrypt your squad clearance cipher.",
      },
    },
    "Textile Lab": {
      id: "Textile Lab",
      name: "Textile Lab",
      floorId: "floor-1",
      type: "NORMAL",
      position: { x: 75, y: 35 },
      riddle: {
        title: "Textile & Material Lab",
        text: "Threads of fabric and weave align on cutting tables. Inquire with the textile studio supervisor.",
        hint: "Floor 1 Textile Lab. Present your squad status.",
      },
      codeSource: "TEACHER",
      nextNodes: ["401A"],
      puzzleLocation: {
        clue: "Fragment cached near the fabric swatch library in Textile Lab.",
        hint: "Lower bin.",
        pieceId: "PIECE_THETA",
      },
    },
    "503": {
      id: "503",
      name: "503",
      floorId: "floor-5",
      type: "NORMAL",
      position: { x: 50, y: 65 },
      riddle: {
        title: "The High Art Gallery (Room 503)",
        text: "Ascend to the top deck where digital canvases glow. Speak with the studio instructor.",
        hint: "Floor 5, Room 503. Request clearance.",
      },
      codeSource: "TEACHER",
      nextNodes: ["Staff Lunch", "305"],
      puzzleLocation: {
        clue: "Fragment placed behind the gallery easel in Room 503.",
        hint: "Mounted near display rail.",
        pieceId: "PIECE_LAMBDA",
      },
    },
    "305": {
      id: "305",
      name: "305",
      floorId: "floor-3",
      type: "NORMAL",
      position: { x: 25, y: 45 },
      riddle: {
        title: "Rapid Prototyping Workshop (Room 305)",
        text: "Where molten strands build physical models. A cipher is concealed near the 3D printers.",
        hint: "Floor 3, Room 305. Check under the 3D printer table.",
      },
      codeSource: "HIDDEN",
      nextNodes: ["Staff room", "Staff Lunch"],
      puzzleLocation: {
        clue: "Cached inside the storage bin under the 3D printer table in Room 305.",
        hint: "Blue filament box.",
        pieceId: "PIECE_MU",
      },
    },
    "402": {
      id: "402",
      name: "402",
      floorId: "floor-4",
      type: "NORMAL",
      position: { x: 80, y: 25 },
      riddle: {
        title: "Sound Synthesis Bay (Room 402)",
        text: "Audio waves and synthesized beats are mixed here. Locate the hidden cipher token on the mixer station.",
        hint: "Floor 4, Room 402. Check the audio mixer console.",
      },
      codeSource: "HIDDEN",
      nextNodes: ["Reception"],
      puzzleLocation: {
        clue: "Fragment taped under the audio monitor stand in Room 402.",
        hint: "Right acoustic baffle.",
        pieceId: "PIECE_NU",
      },
    },
    "Library": {
      id: "Library",
      name: "Library",
      floorId: "floor-3",
      type: "NORMAL",
      position: { x: 50, y: 25 },
      riddle: {
        title: "Campus Library",
        text: "Shelves of volumes stand in silent rows. Inquire with the librarian at the circulation desk.",
        hint: "Floor 3 Library. Ask the librarian for the book cipher.",
      },
      codeSource: "TEACHER",
      nextNodes: ["Audi", "503"],
      puzzleLocation: {
        clue: "Fragment placed inside the reference book catalog in the Library.",
        hint: "Behind section 700.",
        pieceId: "PIECE_PI",
      },
    },
    "Canteen": {
      id: "Canteen",
      name: "Canteen",
      floorId: "floor-1",
      type: "NORMAL",
      position: { x: 25, y: 70 },
      riddle: {
        title: "Campus Canteen",
        text: "Where students gather for lunch and conversation. Scour near the central seating area for the token.",
        hint: "Floor 1 Canteen. Search near the central seating area.",
      },
      codeSource: "HIDDEN",
      nextNodes: ["Library"],
      puzzleLocation: {
        clue: "Fragment concealed behind the bulletin board in the Canteen.",
        hint: "Right notice board border.",
        pieceId: "PIECE_OMICRON",
      },
    },
    "Reception": {
      id: "Reception",
      name: "Reception",
      floorId: "floor-1",
      type: "NORMAL",
      position: { x: 50, y: 70 },
      riddle: {
        title: "Campus Reception",
        text: "Where visitors enter the campus perimeter. Check in with the front desk officer.",
        hint: "Floor 1 Reception. Speak with the front desk executive.",
      },
      codeSource: "TEACHER",
      nextNodes: ["401A", "Audi"],
      puzzleLocation: {
        clue: "Fragment cached near the reception directory board.",
        hint: "Behind the campus map plaque.",
        pieceId: "PIECE_XI",
      },
    },
    "Photo Lab": {
      id: "Photo Lab",
      name: "Photo Lab",
      floorId: "floor-1",
      type: "NORMAL",
      position: { x: 25, y: 35 },
      riddle: {
        title: "Photo Lab Studio",
        text: "Where shutter speed captures frozen time. Search near the tripod storage bay in the Photo Lab.",
        hint: "Floor 1 Photo Lab. Search the lighting tripod rack.",
      },
      codeSource: "HIDDEN",
      nextNodes: ["Staff room"],
      puzzleLocation: {
        clue: "Fragment taped beneath the backdrop roll in Photo Lab.",
        hint: "Lower bracket.",
        pieceId: "PIECE_RHO",
      },
    },
    "206": {
      id: "206",
      name: "206",
      floorId: "floor-2",
      type: "NORMAL",
      position: { x: 50, y: 70 },
      riddle: {
        title: "Room 206 Computer Graphics",
        text: "Where textures and shading render in full resolution. Locate the cipher token on the peripheral shelf.",
        hint: "Floor 2, Room 206. Check near the graphics tablet storage.",
      },
      codeSource: "HIDDEN",
      nextNodes: ["Reception"],
      puzzleLocation: {
        clue: "Fragment cached inside the tablet storage cabinet in Room 206.",
        hint: "Bottom shelf.",
        pieceId: "PIECE_TAU",
      },
    },
  },
  treasure: {
    title: "THE ICAT CYBER VAULT OF 2026",
    clue: "All fragments unite to expose the hidden relic. The true treasure lies in the collaborative synergy of your squad!",
    hint: "Present your assembled physical artifact to the Event Director at the Ground Floor Auditorium to claim the Grand Trophy.",
    finalMessage: "MISSION ACCOMPLISHED: Squad cleared all sectors, breached Sector 401A, and unlocked the Master Vault in the Auditorium!",
  },
  createdAt: Date.now(),
  updatedAt: Date.now(),
};

export const ICAT_2026_SECRETS: HuntSecrets = {
  huntId: ICAT_2026_HUNT_ID,
  codes: {
    "202": { code: "ALPHA202" },
    "Vice principal cabin": { code: "VICEPRIN" },
    "401B": { code: "VR401B" },
    "Staff room": { code: "STAFFROOM" },
    "306": { code: "UIUX306" },
    "Staff Lunch": { code: "PANTRY" },
    "Game Lounge": { code: "LOUNGE" },
    "Audi": { code: "AUDITORIUM" },
    "201": { code: "STUDIO201" },
    "F.L.": { code: "FASHIONLAB" },
    "401A": { code: "OVERRIDE401A", minigameScoreThreshold: 850 },
    "Textile Lab": { code: "TEXTILE" },
    "503": { code: "SYNAPSE503" },
    "305": { code: "MATRIX305" },
    "402": { code: "AUDIO402" },
    "Library": { code: "LIBRARY" },
    "Canteen": { code: "CAFE" },
    "Reception": { code: "RECEPTION" },
    "Photo Lab": { code: "PHOTOLAB" },
    "206": { code: "CG206" },
  },
  treasureSecret: "AUDITORIUM",
  updatedAt: Date.now(),
};
