import { Hunt, HuntSecrets } from "./types";

export const ICAT_2026_HUNT_ID = "icat-2026";

export const ICAT_2026_HUNT_DATA: Hunt = {
  id: ICAT_2026_HUNT_ID,
  name: "ICAT Bangalore Cyber Hunt 2026",
  slug: "icat-2026",
  status: "active",
  theme: "cyberpunk-vault",
  startingNodeId: "202",
  totalFloors: 5,
  floors: [
    {
      id: "floor-1",
      floorNumber: 1,
      name: "Floor 1 - Foundation & Audio Studios",
      shortName: "FL 1",
      nodeIds: ["101", "102"],
    },
    {
      id: "floor-2",
      floorNumber: 2,
      name: "Floor 2 - Digital Media & Animation Labs",
      shortName: "FL 2",
      nodeIds: ["202"],
    },
    {
      id: "floor-3",
      floorNumber: 3,
      name: "Floor 3 - Game Design & AR/VR R&D",
      shortName: "FL 3",
      nodeIds: ["301", "305"],
    },
    {
      id: "floor-4",
      floorNumber: 4,
      name: "Floor 4 - Main Server Core & Boss Sector",
      shortName: "FL 4",
      nodeIds: ["401A"],
    },
    {
      id: "floor-5",
      floorNumber: 5,
      name: "Floor 5 - Visual Arts & Master Vault",
      shortName: "FL 5",
      nodeIds: ["503", "505", "FINAL_VAULT"],
    },
  ],
  teams: {
    RED: {
      id: "RED",
      name: "Red Squadron",
      color: "red",
      hex: "#FF2A55",
      routeId: "P1",
      badge: "◈",
    },
    WHITE: {
      id: "WHITE",
      name: "White Phantoms",
      color: "white",
      hex: "#E2E8F0",
      routeId: "P2",
      badge: "◇",
    },
    BLACK: {
      id: "BLACK",
      name: "Black Ops",
      color: "black",
      hex: "#64748B",
      routeId: "P3",
      badge: "◆",
    },
    CYAN: {
      id: "CYAN",
      name: "Cyan Cyber",
      color: "cyan",
      hex: "#00F0FF",
      routeId: "P1",
      badge: "❖",
    },
    BLUE: {
      id: "BLUE",
      name: "Blue Sentinels",
      color: "blue",
      hex: "#3B82F6",
      routeId: "P2",
      badge: "⬡",
    },
  },
  routes: {
    P1: {
      id: "P1",
      name: "Route Alpha (P1)",
      nodes: ["202", "101", "305", "401A", "503", "FINAL_VAULT"],
    },
    P2: {
      id: "P2",
      name: "Route Beta (P2)",
      nodes: ["202", "102", "301", "401A", "505", "FINAL_VAULT"],
    },
    P3: {
      id: "P3",
      name: "Route Gamma (P3)",
      nodes: ["202", "305", "101", "401A", "503", "FINAL_VAULT"],
    },
  },
  nodes: {
    "202": {
      id: "202",
      name: "Room 202 - Digital Media Lab",
      floorId: "floor-2",
      type: "NORMAL",
      position: { x: 50, y: 52 },
      riddle: {
        title: "The Origin Frequency",
        text: "Where frame by frame the static turns to flight, the journey starts in rooms of render light. Seek the faculty warden of the second realm.",
        hint: "Locate Room 202 and ask the designated instructor for your launch code.",
      },
      codeSource: "TEACHER",
      nextNodes: ["101", "102", "305"],
      puzzleLocation: {
        clue: "Physical Fragment ALPHA is secured beneath the animator's lightbox in Room 202.",
        hint: "Search the lower bay beneath the tracing table.",
        pieceId: "PIECE_ALPHA",
      },
    },
    "101": {
      id: "101",
      name: "Room 101 - Acoustic Synthesis Bay",
      floorId: "floor-1",
      type: "NORMAL",
      position: { x: 32, y: 48 },
      riddle: {
        title: "Echoes in the Sub-Level",
        text: "Descend to where frequencies are sculpted in dark foam. The secret cipher rests in plain sight where audio waveforms are monitored.",
        hint: "Head to Floor 1, Room 101. Inspect the physical token hidden on the podium.",
      },
      codeSource: "HIDDEN",
      nextNodes: ["305", "401A"],
      puzzleLocation: {
        clue: "Physical Fragment BETA is hidden beneath the main audio console in Room 101.",
        hint: "Feel along the underside edge of the acoustic mixing station.",
        pieceId: "PIECE_BETA",
      },
    },
    "102": {
      id: "102",
      name: "Room 102 - Foley & Broadcast Chamber",
      floorId: "floor-1",
      type: "NORMAL",
      position: { x: 68, y: 48 },
      riddle: {
        title: "The Soundstage Cipher",
        text: "Where footsteps crunch on gravel indoors, look beneath the corner station where broadcast feeds are synced.",
        hint: "Inspect the corner desk beside the reference monitors in Room 102.",
      },
      codeSource: "HIDDEN",
      nextNodes: ["301", "401A"],
      puzzleLocation: {
        clue: "Physical Fragment BETA is taped under the sound engineer's desk in Room 102.",
        hint: "Right-hand support leg.",
        pieceId: "PIECE_BETA",
      },
    },
    "301": {
      id: "301",
      name: "Room 301 - Game Physics & Logic Lab",
      floorId: "floor-3",
      type: "NORMAL",
      position: { x: 35, y: 50 },
      riddle: {
        title: "The Algorithm Gateway",
        text: "Climb to the third plane where collision vectors calculate. Present your clearance badge to the faculty overseer.",
        hint: "Room 301 on Floor 3. Speak with the lab supervisor.",
      },
      codeSource: "TEACHER",
      nextNodes: ["401A"],
      puzzleLocation: {
        clue: "Physical Fragment GAMMA is secured behind the logic demonstration board in Room 301.",
        hint: "Inspect behind the framed system architecture diagram.",
        pieceId: "PIECE_GAMMA",
      },
    },
    "305": {
      id: "305",
      name: "Room 305 - Rapid Prototyping Workshop",
      floorId: "floor-3",
      type: "NORMAL",
      position: { x: 65, y: 50 },
      riddle: {
        title: "The Resin Foundry",
        text: "Layer by layer, molten strands create physical forms. A glowing token is concealed near the 3D fabrication printers.",
        hint: "Room 305 on Floor 3. Check the base of the printing rack.",
      },
      codeSource: "HIDDEN",
      nextNodes: ["401A", "101"],
      puzzleLocation: {
        clue: "Physical Fragment GAMMA is cached inside the storage bin under the 3D printer table in Room 305.",
        hint: "Inside the blue filament compartment.",
        pieceId: "PIECE_GAMMA",
      },
    },
    "401A": {
      id: "401A",
      name: "Sector 401A - Neural Core [BOSS ENCOUNTER]",
      floorId: "floor-4",
      type: "BOSS",
      position: { x: 50, y: 48 },
      riddle: {
        title: "BOSS GATEWAY: Unity Neural Mainframe",
        text: "WARNING: High-security mainframe locked. Travel to Room 401A and breach the cyber defense on the Unity arcade workstation. Achieve the target score (>= 850 PTS) in the Unity game to earn your clearance cipher!",
        hint: "Play the Unity Cyber game in Room 401A (or on your device). Achieving 850+ PTS reveals the secret cipher to decrypt this sector and unlock your next route nodes!",
      },
      codeSource: "MINIGAME",
      nextNodes: ["503", "505"],
      puzzleLocation: {
        clue: "Physical Boss Fragment DELTA is secured beside the main network switch cabinet in Room 401A.",
        hint: "Check the lower cable conduit casing.",
        pieceId: "PIECE_DELTA",
      },
      minigame: {
        gameId: "401A_UNITY_OVERRIDE",
        minimumScore: 850,
        title: "Unity Cyber Mainframe Override",
        instructions: "Play the Unity game in Room 401A or online. Achieve >= 850 PTS to decrypt your squad clearance cipher.",
      },
    },
    "503": {
      id: "503",
      name: "Room 503 - VR Immersion Studio",
      floorId: "floor-5",
      type: "NORMAL",
      position: { x: 30, y: 52 },
      riddle: {
        title: "The Optical Horizon",
        text: "Ascend to the summit where virtual reality lenses align. Seek the faculty keeper who guards the gateway to the vault.",
        hint: "Floor 5, Room 503. Request clearance from the studio supervisor.",
      },
      codeSource: "TEACHER",
      nextNodes: ["FINAL_VAULT"],
      puzzleLocation: {
        clue: "Physical Fragment EPSILON is placed behind the ceiling projector bracket in Room 503.",
        hint: "Mounted high near the cable bracket.",
        pieceId: "PIECE_EPSILON",
      },
    },
    "505": {
      id: "505",
      name: "Room 505 - Concept Art & Matte Atelier",
      floorId: "floor-5",
      type: "NORMAL",
      position: { x: 70, y: 52 },
      riddle: {
        title: "The Palette of Shadows",
        text: "Where digital brushes blend endless colors, look behind the master lighting softbox in the photography wing.",
        hint: "Room 505 on Floor 5. Check the studio gear closet.",
      },
      codeSource: "HIDDEN",
      nextNodes: ["FINAL_VAULT"],
      puzzleLocation: {
        clue: "Physical Fragment EPSILON is placed inside the equipment cabinet in Room 505.",
        hint: "Bottom shelf behind the backdrop fabric.",
        pieceId: "PIECE_EPSILON",
      },
    },
    "FINAL_VAULT": {
      id: "FINAL_VAULT",
      name: "Master Cyber Vault - The Nexus",
      floorId: "floor-5",
      type: "FINAL",
      position: { x: 50, y: 25 },
      riddle: {
        title: "FINAL DESTINATION: The Cyber Vault",
        text: "All pathways converge here. The physical puzzle pieces in your hands contain the final coordinates. Locate the sealed master vault and enter the ultimate key to claim victory!",
        hint: "Piece together the physical fragments collected from each floor to reveal the final cipher code.",
      },
      codeSource: "HIDDEN",
      nextNodes: [],
      puzzleLocation: {
        clue: "THE MASTER PRIZE: Present your completed physical puzzle to the Grand Arbiter at the central dais.",
        hint: "Victory awaits the triumphant team.",
        pieceId: "PIECE_OMEGA",
      },
    },
  },
  treasure: {
    title: "THE ICAT CYBER VAULT OF 2026",
    clue: "All fragments unite to expose the hidden relic. The true treasure lies in the collaborative synergy of your squad!",
    hint: "Present your assembled physical artifact to the Event Director at the Ground Floor Auditorium to claim the Grand Trophy.",
    finalMessage: "MISSION ACCOMPLISHED: Team cleared all sectors, bypassed Boss Mainframe 401A, and unlocked the Cyber Vault!",
  },
  createdAt: Date.now(),
  updatedAt: Date.now(),
};

export const ICAT_2026_SECRETS: HuntSecrets = {
  huntId: ICAT_2026_HUNT_ID,
  codes: {
    "202": { code: "ALPHA202" },
    "101": { code: "CIPHER101" },
    "102": { code: "VECTOR102" },
    "301": { code: "NEXUS301" },
    "305": { code: "MATRIX305" },
    "401A": { code: "OVERRIDE401A", minigameScoreThreshold: 850 },
    "503": { code: "SYNAPSE503" },
    "505": { code: "QUANTUM505" },
    "FINAL_VAULT": { code: "TREASURE2026" },
  },
  treasureSecret: "TREASURE2026",
  updatedAt: Date.now(),
};
