import { Hunt, HuntSecrets } from "./types";

export const ICAT_2026_HUNT_ID = "icat-2026";

export const ICAT_2026_HUNT_DATA: Hunt = {
  id: ICAT_2026_HUNT_ID,
  name: "ICAT Bangalore Cyber Hunt 2026",
  slug: "icat-2026",
  status: "active",
  theme: "cyberpunk-vault",
  startingNodeId: "202",
  totalFloors: 5,
  floors: [
    {
      id: "floor-1",
      floorNumber: 1,
      name: "Floor 1 - Reception, Studios & Auditorium",
      shortName: "FL 1",
      nodeIds: ["Reception", "Audi", "Canteen", "Textile Lab", "Photo Lab"],
    },
    {
      id: "floor-2",
      floorNumber: 2,
      name: "Floor 2 - Digital Media & Leadership Core",
      shortName: "FL 2",
      nodeIds: ["202", "201", "206", "Vice-Prin"],
    },
    {
      id: "floor-3",
      floorNumber: 3,
      name: "Floor 3 - Game Design, Library & Staff Sector",
      shortName: "FL 3",
      nodeIds: ["303", "305", "306", "Lib", "Staff Lunch"],
    },
    {
      id: "floor-4",
      floorNumber: 4,
      name: "Floor 4 - Main Server Core & Boss Sector",
      shortName: "FL 4",
      nodeIds: ["401A", "401B", "402", "S.R."],
    },
    {
      id: "floor-5",
      floorNumber: 5,
      name: "Floor 5 - Visual Arts, Film Lab & Game Lounge",
      shortName: "FL 5",
      nodeIds: ["503", "Game Lounge", "F.L."],
    },
  ],
  teams: {
    RED: {
      id: "RED",
      name: "Red Squadron",
      color: "red",
      hex: "#FF2A55",
      routeId: "P1",
      badge: "◈",
    },
    WHITE: {
      id: "WHITE",
      name: "White Phantoms",
      color: "white",
      hex: "#E2E8F0",
      routeId: "P2",
      badge: "◇",
    },
    BLACK: {
      id: "BLACK",
      name: "Black Ops",
      color: "black",
      hex: "#64748B",
      routeId: "P3",
      badge: "◆",
    },
    CYAN: {
      id: "CYAN",
      name: "Cyan Cyber",
      color: "cyan",
      hex: "#00F0FF",
      routeId: "P1",
      badge: "❖",
    },
    BLUE: {
      id: "BLUE",
      name: "Blue Sentinels",
      color: "blue",
      hex: "#3B82F6",
      routeId: "P2",
      badge: "⬡",
    },
  },
  routes: {
    P1: {
      id: "P1",
      name: "Route Alpha (P1)",
      nodes: [
        "202",
        "Vice-Prin",
        "401B",
        "S.R.",
        "306",
        "Staff Lunch",
        "Game Lounge",
        "Textile Lab",
        "401A",
        "F.L.",
        "201",
        "Audi",
      ],
    },
    P2: {
      id: "P2",
      name: "Route Beta (P2)",
      nodes: [
        "202",
        "Game Lounge",
        "503",
        "Staff Lunch",
        "305",
        "S.R.",
        "402",
        "Reception",
        "401A",
        "Canteen",
        "Lib",
        "Audi",
      ],
    },
    P3: {
      id: "P3",
      name: "Route Gamma (P3)",
      nodes: [
        "202",
        "Photo Lab",
        "S.R.",
        "303",
        "Lib",
        "503",
        "305",
        "Staff Lunch",
        "401A",
        "206",
        "Reception",
        "Audi",
      ],
    },
  },
  nodes: {
    "202": {
      id: "202",
      name: "Room 202 - Digital Media Lab",
      floorId: "floor-2",
      type: "NORMAL",
      position: { x: 45, y: 40 },
      riddle: {
        title: "Starting Point: The Genesis Station",
        text: "Where frame by frame the motion awakens. Present your clearance badge to the lab faculty coordinator in Room 202 to initiate your route.",
        hint: "Locate Room 202 on Floor 2. Request the launch cipher.",
      },
      codeSource: "TEACHER",
      nextNodes: ["Vice-Prin", "Game Lounge", "Photo Lab"],
      puzzleLocation: {
        clue: "Physical Fragment ALPHA is cached under the animation lightbox in Room 202.",
        hint: "Lower cabinet bay.",
        pieceId: "PIECE_ALPHA",
      },
    },
    "Vice-Prin": {
      id: "Vice-Prin",
      name: "Vice Principal Office",
      floorId: "floor-2",
      type: "NORMAL",
      position: { x: 75, y: 35 },
      riddle: {
        title: "The Executive Sanctum",
        text: "Where campus governance convenes and leadership charters are drafted. Present yourself respectfully to request the leadership cipher.",
        hint: "Floor 2 Vice Principal office. Ask the office executive.",
      },
      codeSource: "TEACHER",
      nextNodes: ["401B"],
      puzzleLocation: {
        clue: "Physical clue hidden near the entrance plaque of the executive office.",
        hint: "Beside the welcome registry.",
        pieceId: "PIECE_BETA",
      },
    },
    "401B": {
      id: "401B",
      name: "Room 401B - VR Studio",
      floorId: "floor-4",
      type: "NORMAL",
      position: { x: 70, y: 55 },
      riddle: {
        title: "Virtual Reality Bay",
        text: "Where virtual headsets simulate distant dimensions. Scour the room for a hidden cipher token near the sensor stands.",
        hint: "Floor 4, Room 401B. Inspect the VR headset staging table.",
      },
      codeSource: "HIDDEN",
      nextNodes: ["S.R."],
      puzzleLocation: {
        clue: "Fragment taped under the primary VR tracking stand in 401B.",
        hint: "Right support strut.",
        pieceId: "PIECE_GAMMA",
      },
    },
    "S.R.": {
      id: "S.R.",
      name: "Server Room / Staff Nexus",
      floorId: "floor-4",
      type: "NORMAL",
      position: { x: 30, y: 45 },
      riddle: {
        title: "The Mainframe Core",
        text: "Blinking LED arrays hum in cool air where campus network traffic routes. Locate the security token near the firewall cabinet.",
        hint: "Floor 4 Server Room. Check near the network rack casing.",
      },
      codeSource: "HIDDEN",
      nextNodes: ["306", "402", "303"],
      puzzleLocation: {
        clue: "Secured near the network diagnostic table in Server Room.",
        hint: "Lower shelf.",
        pieceId: "PIECE_DELTA",
      },
    },
    "306": {
      id: "306",
      name: "Room 306 - UI/UX Interactive Lab",
      floorId: "floor-3",
      type: "NORMAL",
      position: { x: 75, y: 45 },
      riddle: {
        title: "Interface Architecture",
        text: "Where wireframes transform into digital interactions. Request clearance from the lab coordinator in Room 306.",
        hint: "Floor 3, Room 306. Inquire with the lab supervisor.",
      },
      codeSource: "TEACHER",
      nextNodes: ["Staff Lunch"],
      puzzleLocation: {
        clue: "Fragment placed behind the UI design whiteboard in 306.",
        hint: "Behind the marker tray.",
        pieceId: "PIECE_EPSILON",
      },
    },
    "Staff Lunch": {
      id: "Staff Lunch",
      name: "Staff Lunch Room & Pantry",
      floorId: "floor-3",
      type: "NORMAL",
      position: { x: 50, y: 70 },
      riddle: {
        title: "The Refreshment Outpost",
        text: "Where faculties recharge between lectures over coffee and meals. A hidden cipher is discreetly placed near the coffee counter.",
        hint: "Floor 3 Staff Lunch Room. Search the refreshment shelf.",
      },
      codeSource: "HIDDEN",
      nextNodes: ["Game Lounge", "305", "401A"],
      puzzleLocation: {
        clue: "Fragment taped under the side utility counter in Staff Lunch.",
        hint: "Underneath the corner counter.",
        pieceId: "PIECE_ZETA",
      },
    },
    "Game Lounge": {
      id: "Game Lounge",
      name: "Game Lounge [G.L.]",
      floorId: "floor-5",
      type: "NORMAL",
      position: { x: 25, y: 45 },
      riddle: {
        title: "The Gamer's Haven",
        text: "Where controllers click and high scores reign supreme. Check near the console display stations for your squad cipher.",
        hint: "Floor 5 Game Lounge. Inspect the couch or gaming station shelf.",
      },
      codeSource: "HIDDEN",
      nextNodes: ["Textile Lab", "503"],
      puzzleLocation: {
        clue: "Fragment concealed behind the retro console display in Game Lounge.",
        hint: "Beside the arcade TV cabinet.",
        pieceId: "PIECE_ETA",
      },
    },
    "Textile Lab": {
      id: "Textile Lab",
      name: "Textile & Material Lab",
      floorId: "floor-1",
      type: "NORMAL",
      position: { x: 75, y: 35 },
      riddle: {
        title: "The Loom of Patterns",
        text: "Threads of fabric and weave align on cutting tables. Inquire with the textile studio supervisor.",
        hint: "Floor 1 Textile Lab. Present your squad status.",
      },
      codeSource: "TEACHER",
      nextNodes: ["401A"],
      puzzleLocation: {
        clue: "Fragment cached near the fabric swatch library in Textile Lab.",
        hint: "Lower bin.",
        pieceId: "PIECE_THETA",
      },
    },
    "401A": {
      id: "401A",
      name: "Sector 401A - Neural Core [BOSS ENCOUNTER]",
      floorId: "floor-4",
      type: "BOSS",
      position: { x: 50, y: 25 },
      riddle: {
        title: "BOSS GATEWAY: Unity Mainframe Challenge",
        text: "WARNING: High-security cyber defense active! Travel to Room 401A. The Unity Arcade Challenge Station is loaded on the workstation. Achieve >= 850 PTS in the Unity game to receive your clearance cipher!",
        hint: "Play the Unity Arcade Game in Room 401A (or web test). Score >= 850 PTS to unlock the secret cipher to decrypt this sector and unlock your next route nodes!",
      },
      codeSource: "MINIGAME",
      nextNodes: ["F.L.", "Canteen", "206"],
      puzzleLocation: {
        clue: "Physical Boss Fragment DELTA is secured beside the main network switch cabinet in Room 401A.",
        hint: "Check the lower cable conduit casing.",
        pieceId: "PIECE_DELTA",
      },
      minigame: {
        gameId: "401A_UNITY_OVERRIDE",
        minimumScore: 850,
        title: "Unity Cyber Mainframe Override",
        instructions: "Play the Unity game in Room 401A or online. Achieve >= 850 PTS to decrypt your squad clearance cipher.",
      },
    },
    "F.L.": {
      id: "F.L.",
      name: "Fashion & Film Studio [F.L.]",
      floorId: "floor-5",
      type: "NORMAL",
      position: { x: 70, y: 45 },
      riddle: {
        title: "The Cinematic Studio",
        text: "Where studio lights flare and film cameras roll. Search near the green screen equipment racks.",
        hint: "Floor 5 Fashion/Film Lab. Check the lighting stand base.",
      },
      codeSource: "HIDDEN",
      nextNodes: ["201"],
      puzzleLocation: {
        clue: "Fragment placed behind the primary studio softbox in Film Lab.",
        hint: "Behind backdrop rail.",
        pieceId: "PIECE_IOTA",
      },
    },
    "201": {
      id: "201",
      name: "Room 201 - Foundation Atelier",
      floorId: "floor-2",
      type: "NORMAL",
      position: { x: 25, y: 40 },
      riddle: {
        title: "The Sketching Canvas",
        text: "Where line, perspective and shading begin. Ask the foundation instructor for the penultimate clearance cipher.",
        hint: "Floor 2, Room 201. Inquire with the studio supervisor.",
      },
      codeSource: "TEACHER",
      nextNodes: ["Audi"],
      puzzleLocation: {
        clue: "Fragment secured behind the drafting board in Room 201.",
        hint: "Left easel support.",
        pieceId: "PIECE_KAPPA",
      },
    },
    "503": {
      id: "503",
      name: "Room 503 - Visual Arts Studio",
      floorId: "floor-5",
      type: "NORMAL",
      position: { x: 50, y: 65 },
      riddle: {
        title: "The High Art Gallery",
        text: "Ascend to the top deck where digital canvases glow. Speak with the studio instructor.",
        hint: "Floor 5, Room 503. Request clearance.",
      },
      codeSource: "TEACHER",
      nextNodes: ["Staff Lunch", "305"],
      puzzleLocation: {
        clue: "Fragment placed behind the gallery easel in Room 503.",
        hint: "Mounted near display rail.",
        pieceId: "PIECE_LAMBDA",
      },
    },
    "305": {
      id: "305",
      name: "Room 305 - Rapid Prototyping Workshop",
      floorId: "floor-3",
      type: "NORMAL",
      position: { x: 25, y: 45 },
      riddle: {
        title: "The 3D Fabrication Bay",
        text: "Where molten strands build physical models. A cipher is concealed near the 3D printers.",
        hint: "Floor 3, Room 305. Check under the 3D printer table.",
      },
      codeSource: "HIDDEN",
      nextNodes: ["S.R.", "Staff Lunch"],
      puzzleLocation: {
        clue: "Cached inside the storage bin under the 3D printer table in Room 305.",
        hint: "Blue filament box.",
        pieceId: "PIECE_MU",
      },
    },
    "402": {
      id: "402",
      name: "Room 402 - Sound Synthesis Bay",
      floorId: "floor-4",
      type: "NORMAL",
      position: { x: 80, y: 25 },
      riddle: {
        title: "The Frequency Chamber",
        text: "Audio waves and synthesized beats are mixed here. Locate the hidden cipher token on the mixer station.",
        hint: "Floor 4, Room 402. Check the audio mixer console.",
      },
      codeSource: "HIDDEN",
      nextNodes: ["Reception"],
      puzzleLocation: {
        clue: "Fragment taped under the audio monitor stand in 402.",
        hint: "Right acoustic baffle.",
        pieceId: "PIECE_NU",
      },
    },
    "Reception": {
      id: "Reception",
      name: "Campus Front Reception",
      floorId: "floor-1",
      type: "NORMAL",
      position: { x: 50, y: 70 },
      riddle: {
        title: "The Ground Gateway",
        text: "Where visitors enter the campus perimeter. Check in with the front desk officer.",
        hint: "Floor 1 Reception. Speak with the front desk executive.",
      },
      codeSource: "TEACHER",
      nextNodes: ["401A", "Audi"],
      puzzleLocation: {
        clue: "Fragment cached near the reception directory board.",
        hint: "Behind the campus map plaque.",
        pieceId: "PIECE_XI",
      },
    },
    "Canteen": {
      id: "Canteen",
      name: "Campus Cafeteria & Canteen",
      floorId: "floor-1",
      type: "NORMAL",
      position: { x: 25, y: 70 },
      riddle: {
        title: "The Social Hub",
        text: "Where students gather for lunch and conversation. Scour near the main order board for the token.",
        hint: "Floor 1 Canteen. Search near the central seating pillar.",
      },
      codeSource: "HIDDEN",
      nextNodes: ["Lib"],
      puzzleLocation: {
        clue: "Fragment concealed behind the bulletin board in the Canteen.",
        hint: "Right notice board border.",
        pieceId: "PIECE_OMICRON",
      },
    },
    "Lib": {
      id: "Lib",
      name: "Campus Research Library",
      floorId: "floor-3",
      type: "NORMAL",
      position: { x: 50, y: 25 },
      riddle: {
        title: "The Repository of Knowledge",
        text: "Shelves of volumes stand in silent rows. Inquire with the librarian at the circulation desk.",
        hint: "Floor 3 Library. Ask the librarian for the book cipher.",
      },
      codeSource: "TEACHER",
      nextNodes: ["Audi", "503"],
      puzzleLocation: {
        clue: "Fragment placed inside the reference book catalog in the Library.",
        hint: "Behind section 700.",
        pieceId: "PIECE_PI",
      },
    },
    "Photo Lab": {
      id: "Photo Lab",
      name: "Photography Studio & Darkroom",
      floorId: "floor-1",
      type: "NORMAL",
      position: { x: 25, y: 35 },
      riddle: {
        title: "The Darkroom Lens",
        text: "Where shutter speed captures frozen time. Search near the tripod storage bay.",
        hint: "Floor 1 Photography Studio. Search the lighting tripod rack.",
      },
      codeSource: "HIDDEN",
      nextNodes: ["S.R."],
      puzzleLocation: {
        clue: "Fragment taped beneath the backdrop roll in Photo Lab.",
        hint: "Lower bracket.",
        pieceId: "PIECE_RHO",
      },
    },
    "303": {
      id: "303",
      name: "Room 303 - Game Art Lab",
      floorId: "floor-3",
      type: "NORMAL",
      position: { x: 25, y: 70 },
      riddle: {
        title: "The Polygon Sculptor",
        text: "3D characters and digital environments take shape here. Request clearance from the lab faculty.",
        hint: "Floor 3, Room 303. Speak with the instructor.",
      },
      codeSource: "TEACHER",
      nextNodes: ["Lib"],
      puzzleLocation: {
        clue: "Fragment placed under the main workstation table in 303.",
        hint: "Center row.",
        pieceId: "PIECE_SIGMA",
      },
    },
    "206": {
      id: "206",
      name: "Room 206 - Computer Graphics Lab",
      floorId: "floor-2",
      type: "NORMAL",
      position: { x: 50, y: 70 },
      riddle: {
        title: "The Pixel Forge",
        text: "Where textures and shading render in full resolution. Locate the cipher token on the peripheral shelf.",
        hint: "Floor 2, Room 206. Check near the graphics tablet storage.",
      },
      codeSource: "HIDDEN",
      nextNodes: ["Reception"],
      puzzleLocation: {
        clue: "Fragment cached inside the tablet storage cabinet in 206.",
        hint: "Bottom shelf.",
        pieceId: "PIECE_TAU",
      },
    },
    "Audi": {
      id: "Audi",
      name: "Campus Grand Auditorium [FINAL VAULT]",
      floorId: "floor-1",
      type: "FINAL",
      position: { x: 50, y: 20 },
      riddle: {
        title: "FINAL DESTINATION: The Grand Auditorium",
        text: "All paths converge at the Grand Auditorium! Assemble all physical puzzle pieces retrieved across campus to reveal the ultimate victory key and claim the ICAT 2026 Grand Trophy!",
        hint: "Enter the Grand Auditorium on Floor 1 and submit the ultimate victory cipher.",
      },
      codeSource: "HIDDEN",
      nextNodes: [],
      puzzleLocation: {
        clue: "THE MASTER PRIZE: Present your completed physical puzzle to the Grand Arbiter on the Auditorium stage.",
        hint: "Victory awaits!",
        pieceId: "PIECE_OMEGA",
      },
    },
  },
  treasure: {
    title: "THE ICAT CYBER VAULT OF 2026",
    clue: "All fragments unite to expose the hidden relic. The true treasure lies in the collaborative synergy of your squad!",
    hint: "Present your assembled physical artifact to the Event Director at the Ground Floor Auditorium to claim the Grand Trophy.",
    finalMessage: "MISSION ACCOMPLISHED: Squad cleared all sectors, breached Sector 401A, and unlocked the Master Vault in the Auditorium!",
  },
  createdAt: Date.now(),
  updatedAt: Date.now(),
};

export const ICAT_2026_SECRETS: HuntSecrets = {
  huntId: ICAT_2026_HUNT_ID,
  codes: {
    "202": { code: "ALPHA202" },
    "Vice-Prin": { code: "VICEPRIN" },
    "401B": { code: "VR401B" },
    "S.R.": { code: "SERVER" },
    "306": { code: "UIUX306" },
    "Staff Lunch": { code: "PANTRY" },
    "Game Lounge": { code: "LOUNGE" },
    "Textile Lab": { code: "TEXTILE" },
    "401A": { code: "OVERRIDE401A", minigameScoreThreshold: 850 },
    "F.L.": { code: "FILMLAB" },
    "201": { code: "STUDIO201" },
    "Audi": { code: "AUDITORIUM" },
    "503": { code: "SYNAPSE503" },
    "305": { code: "MATRIX305" },
    "402": { code: "AUDIO402" },
    "Reception": { code: "RECEPTION" },
    "Canteen": { code: "CAFE" },
    "Lib": { code: "LIBRARY" },
    "Photo Lab": { code: "PHOTOLAB" },
    "303": { code: "GAME303" },
    "206": { code: "CG206" },
  },
  treasureSecret: "AUDITORIUM",
  updatedAt: Date.now(),
};
